# Übung 2.1

**Gruppenname:**

*Name Ihrer Gruppe*

Gehen Sie wie folgt vor:

1. Bitte benennen Sie jetzt dieses Jupyter Notebook um (z.B. über `File -> Rename`):

   Namensschema: `Gruppenname-X`. Ersetzen Sie "X" mit der oben angegebenen Nummer der Übung.

   - Beispiel 1: Team REZA bearbeitet Übung 2. Das Notebook heißt: REZA-2.
   - Beispiel 2: Sie sind keinem Team zugeordnet (nicht empfehlenswert) und bearbeiten Übung 2: Ihr Notebook heißt: Nachname-2.


2. Tragen Sie Ihren Gruppennamen auch ganz oben bei "Name Ihrer Gruppe" ein.

3. Bearbeiten Sie dann dieses Notebook. Vergessen Sie dabei nicht, das Jupyter Notebook regelmäßig zu speichern (z.B. über `Strg + S` oder über `File -> Save and Checkpoint`).

In dieser Übung werden wir uns mit wichtigen Software-Werkzeugen für Data Science vertraut machen. In diesem Notebook finden Sie Übung 2.1, die sich mit Numpy beschäftigt. Übung 2.2 (Pandas) finden Sie bei ILIAs.

Diese Übungen dienen dazu, Sie auf verschiedene Aspekte der in den kommenden Wochen in den Übungen genutzten Werkzeuge aufmerksam zu machen.

* Wenn Sie in Ihrem bisherigen Studienverlauf noch nicht viel mit Python zu tun hatten, schauen Sie doch gerne einmal bei ILIAS unter "Lernressourcen" nach. Ich habe Ihnen dort Inhalte hinterlegt, die Sie nutzen können, um sich im Selbststudium mit Python vertrauter zu machen.

## 2.1.1 Shapes und Co.

Bei vielen Data Science Projekten werden Daten zunächst zugänglich gemacht, sodass sie als Numpy Arrays vorliegen. Das Verständnis von *Shapes* solcher Arrays ist eine wichtige Voraussetzung für eine produktive Arbeit mit diesen Datenstrukturen.

Nehmen Sie die Folien zur heutigen Vorlesung zur Hand.

**Ihre Aufgaben**

(1) Betrachten Sie den untenstehenden Code. Beantworten Sie: Welchen [Shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) hat das Numpy Array `a`? 

Antwort: (4,)

In [3]:
import numpy as np
a = np.array([5, 10, 15, 20])
b = a.shape
c = a.T
print ("Ist vector 'a' nicht transponiert?", np.array_equal(a, c) )


Ist vector 'a' nicht transponiert? True


(2) Lässt sich das Array `a` als (mathematischen) Vektor interpretieren? Wenn `a` ein Vektor ist, können Sie ihn [transponieren](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)?
Antwort:
Nein, siehe c im Oben.

(3) Betrachten Sie das unten stehende Array `b`. Erzeugen Sie aus `b` bitte zwei neue Arrays `c` und `d`: `c` soll ein Spaltenvektor sein, und `d` soll ein Zeilenvektor sein. Wie gehen Sie vor?

In [9]:
b = np.array([2, 4, 6, 8, 10])
c = b.T
d = b
print(b, c, d)

[ 2  4  6  8 10] [ 2  4  6  8 10] [ 2  4  6  8 10]


Lässt sich `c` bzw. `d` transponieren? Warum?
Antwort: nein, Numpy's transpose() (alias T) stellt(eng. reverse) das shape von array andersrum(. Dies bedeutet für ein 1 dimensionale array wie 'b' keine effect.

(4) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Zeile `k[0, 1] = 10` das Array `m` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Antwort:
Ja, np.array() ist zwar ein dynamisches Feld und k wird sich wie ein Zeiger bei der c++ Sprache verhält. Daher ist 'm' eine Kopie von Zeiger der gewählten Elementen von matrix 'm'. In diesem Fall wurde an der Stelle erste Zeile zweite spalte von Matrix 10 geschrieben.

In [27]:
k = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m = k[:2, 1:3]
k[0, 1] = 10
print ( k, '\n', m)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 [[10  3]
 [ 6  7]]


(5) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Änderung des Arrays `p` der Inhalt von `q` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Antwort:
Nein, weil hier(im zweiten Zeile) explizit die Kopie von zweiten und dritte Element aus erste Spalte von Matrix 'p' gemacht wurde before das Vector P geändert wird.

In [4]:
p = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
q = p[[1, 2], 0]
p[1, 0] = 25
# q = p[[1, 2], 0]

print(q, '\n', p)

[25  9] 
 [[ 1  2  3  4]
 [25  6  7  8]
 [ 9 10 11 12]]


## 2.1.2 Broadcasting - Teil 1

Nehmen Sie sich die Folien zur heutigen Vorlesung zur Hand. Unten sehen Sie eine Operation mit zwei Numpy Arrays `a` und `b`.

**Ihre Aufgaben**

(1) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.
Antwort:
die beiden arrays sind gleich dimension und gleich größ und daher wird auf jedem component des linken arrays aus Komponenten der rechten hingefügt.

In [31]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

# Ihre Vorhersagen
shape = (3,)
ergebnis = np.array([5, 7, 9])
print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



(2) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.
Antwort:
  The new-axis funktioniert wie eine reshape zur Konvertierung array[4,5,6] in einer spalte und damit wegen
  der unterschiedlichen Dimensionen der Operanden füllen sich die beiden Seite der Add operation mit zusätzliche dimension zur Anpassung auf. D.h. 'a' und 'b' bekommen ein shape (3,3) und somit das Ergebnis auch.

In [39]:
a = np.array([1, 2, 3])
# a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])[:, np.newaxis]
bt = np.array([[4, 5, 6],[1,2,3]])[:, np.newaxis]
# print(bt[:].shape)
print(b, '\n', b.shape)
print(a, '\n',a.shape)
c = a + b
shape = (3, 3) # Ihre Vorhersage
ergebnis = np.array([[5,6,7],[6,7,8],[7,8,9]])
print('{}\n'.format('Shape Korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

[[4]
 [5]
 [6]] 
 (3, 1)
[1 2 3] 
 (3,)
Shape Korrekt.

Ergebnis korrekt.



(3) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten?

  * Tragen Sie ihre Voraussage in die Variable `shape` ein.
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

Antwort: The array 'a' ist ein zwei dimensional array mit zwei zeile und drei spalte d.h. sein shape sollte (2,3) andererseits ist array 'b' laut der reshape ein array mit 4 Zeile und jeweils jeder zeile mit ein array mit ein zeile und 3 Spalte also (4,1,3). Nun laut der Broadcastingregeln(die zweite Regel) wird für jede inner
 Zeile zusätzliche Zeile zur Anpassung vom shape des array 'a' auf. d.h. es wird 4 Zeile mit jeweils mit zwei zeile und drei spalte, vor dahin hat array 'a' nach der Regeln (die erste Regel) 3 zusätzliche Zeile bekommen und nun ist die Add Operation machtbar. Ansonsten die Operation '*' funktioniert wie multiply im Numpy als Outer product (kein Matrixprodukt) und das Ergebnis sollte eine array mit 4 Mal zeile jeweils mit dem Resultat von Outer Product von [[1, 0, 0], [0, 0, 2]] * [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]].

In [55]:
a = np.array([[1, 0, 0], [0, 0, 2]])
b = np.ones(12).reshape((4, 1, 3))

# print(np.ones(( 3,3,10)))
# print(np.arange(3).reshape((1,3)))
# print(np.arange(1,6, 2,float))
# d = np.array([[1,2],[3,4]])
# e = np.array([[2,3],[4,1]])
# print(np.dot(d,e))
# print(np.multiply(d,e))
# print(d*e)
c = a * b
shape = (4, 2, 3) # Ihre Vorhersage
ergebnis = np.array([[[1, 0, 0], [0, 0, 2]],[[1, 0, 0], [0, 0, 2]], [[1, 0, 0], [0, 0, 2]],
                     [[1, 0, 0], [0, 0, 2]]]) # Ich vermute, dass sie hierüber länger nachdenken werden.

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



## 2.1.3 Broadcasting Teil 2

Ein häufiger Vorverarbeitungsschritt, der Ihnen in verschiedenen Data Science Projekten begegnen wird, ist die Normierung von Daten. Häufig werden dabei Datensätze, z.B. Zeitreihen, auf Mittelwert $0$ und Standardabweichung $1$ normiert. Dieser Vorgang wird auch *z-scoring* (oder: *Standardisierung*) genannt:

Sei $x_i$ der $i$-te Datenpunkt einer Zeitreihe. Dann ist der z-score dieses Datenpunkts definiert als

$$\tilde{x}_i = \frac{x_i - \bar{x}}{\sigma},$$ 

wobei $\bar{x}$ der Mittelwert sowie $\sigma$ die Standardabweichung der Zeitreihe bezeichnen.

Das in der unten stehenden Code-Zelle definierte Numpy Array `X` enthält 5 Zeitreihen (Spalten) mit je 30 Einträgen (Zeilen). 

* Nutzen Sie Broadcasting sowie [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) und [np.std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html), um die Zeitreihen auf Mittelwert 0 und Varianz 1 zu normieren. Die transformierten Zeitreihen sollen im Numpy Array `Y` gespeichert werden. Dabei schreiben Sie nur eine Zeile Code, um die Zeitreihen zu transformieren.
* Beachten Sie das `axis` Argument bei `np.mean` und `np.std`.

In [70]:
import numpy as np
np.random.seed(0) # seed for reproducibility
X = np.random.random((30, 5)) # Create a 30x5 array of uniformly distributed random values between 0 and 1
# Y = []
# Y.append([(x - np.mean(X)) / np.std(X) for x in X])
# Y = [(x - np.mean(X)) / np.std(X) for x in X]
Y = np.array([((x - np.mean(X)) / np.std(X,axis= 0)) for x in X])
# print(Y)

[[ 0.15341087  0.84291147  0.29601283  0.12932338 -0.29233953]
 [ 0.53992117 -0.29903316  1.22105967  1.69448328 -0.4280483 ]
 [ 1.12052274  0.07657036  0.18488666  1.55221377 -1.48233088]
 [-1.68470802 -2.01592214  1.03172535  1.00116732  1.21399386]
 [ 1.86460735  1.18832729 -0.15620163  1.01003409 -1.32291437]
 [ 0.5161403  -1.50939427  1.39036614  0.04323217 -0.32268796]
 [-0.97831466  1.08579629 -0.17325851  0.21734275 -1.65864764]
 [ 0.42741419  0.41882531  0.34136941  1.62005353  0.57889809]
 [-0.60027791 -0.30131727  0.59966077 -1.68205151  0.52809638]
 [ 0.63843432 -1.23366255 -1.22062003 -0.72824828 -0.49463415]
 [ 0.23854479 -0.29486073  1.53025456 -1.5257546  -1.0171564 ]
 [-1.38937181  0.58753481 -0.82255809 -0.1643356  -0.89718885]
 [-1.39868787 -1.64505322  0.46746475 -1.39069079 -1.0586466 ]
 [-0.56358088  1.2781464  -1.32248389  1.22462144 -1.39775233]
 [ 1.85601214 -0.17124829  1.49308508  0.3534285   0.77275337]
 [-1.87557915 -0.93573742 -1.24856172 -0.80033643 -1.32

(2) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

Antwort: Siehe meine Kommentare unten im zugehörigen Zell. Die Indices sind dabei mit 1 und nicht mit 0 angefangen.

In [15]:
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]]) 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])

print("0: \n",x[2,0])                         # first(0+1) elem from third(2+1) row

print("1: \n",x[[3,3]])                       # the same as x[[[3,3],]] , see the followings to understand

print("2: \n",x[[[0,3],2]])                   # third(2+1) element from 1st(0+1) and 4th(3+1) rows

print("3: \n",x[[[0,3],[2,1]]])               # in 1st and 4th rows, third(2+1) respectively 2nd(1+1) elements                                                 i.e. [x13,x42]
print("4: \n",x[[[0,3],[2,1]],[1]])           # the same as x[[[0,3],[2,1]],[1,1]] --> [[x12,x42], [x32, x22]]                                                 2nd(1+1) elem from 1st(0+1) and 4th(3+1) row. Analogue for[2,1]

print("5: \n",x[[[0,3],[2,1]],[2,1]])         # x[[[0,3],[2,1]],[2,1]] --> [[x13,x42], [x33, x22]]

print("6: \n",x[[[0,3],[2,1]],[[2,1],[1,1]]]) # x[[[0,3],[2,1]],[[2,1],[1,1]]] --->[[x13,x42], [x33, x22]]
                                              # On balance, I would say:
                                              # y = x[rows,cols] ---> [[x11,x13], [x41, x43]]
y = x[rows,cols]
vorhersage = np.array([[0,2],[9,11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

0: 
 6
1: 
 [[ 9 10 11]
 [ 9 10 11]]
2: 
 [ 2 11]
3: 
 [ 2 10]
4: 
 [[ 1 10]
 [ 7  4]]
5: 
 [[ 2 10]
 [ 8  4]]
6: 
 [[ 2 10]
 [ 7  4]]
Ergebnis korrekt.



C:\Users\Montahaee\AppData\Local\Temp\ipykernel_6408\1914293733.py:10: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print("2: \n",x[[[0,3],2]])                   # third(2+1) element from 1st(0+1) and 4th(3+1) rows
C:\Users\Montahaee\AppData\Local\Temp\ipykernel_6408\1914293733.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print("3: \n",x[[[0,3],[2,1]]])               # in 1st and 4th rows, third(2+1) respectively 2nd(1+1) elements                                                 i.e. [x13,x42]


(3) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

Antwort: Wie ich in der letzten Aufgabe klar beschrieben die index array[1, 2] führt dazu, dass all Komponenten zweite(1 +1) und dritte(2 + 1) Spalte vom sliced Matrix, nämlich x[1:], gewählt werden.

In [14]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]]) 
y = x[1:4,[1,2]] # Kombination von Slicing und Advanced Indexing
vorhersage = np.array([[4, 5], [7, 8], [10 , 11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.

