# Übung 2.1

**Gruppenname:**

*Name Ihrer Gruppe*

Gehen Sie wie folgt vor:

1. Bitte benennen Sie jetzt dieses Jupyter Notebook um (z.B. über `File -> Rename`):

   Namensschema: `Gruppenname-X`. Ersetzen Sie "X" mit der oben angegebenen Nummer der Übung.

   - Beispiel 1: Team REZA bearbeitet Übung 2. Das Notebook heißt: REZA-2.
   - Beispiel 2: Sie sind keinem Team zugeordnet (nicht empfehlenswert) und bearbeiten Übung 2: Ihr Notebook heißt: Nachname-2.


2. Tragen Sie Ihren Gruppennamen auch ganz oben bei "Name Ihrer Gruppe" ein.

3. Bearbeiten Sie dann dieses Notebook. Vergessen Sie dabei nicht, das Jupyter Notebook regelmäßig zu speichern (z.B. über `Strg + S` oder über `File -> Save and Checkpoint`).

In dieser Übung werden wir uns mit wichtigen Software-Werkzeugen für Data Science vertraut machen. In diesem Notebook finden Sie Übung 2.1, die sich mit Numpy beschäftigt. Übung 2.2 (Pandas) finden Sie bei ILIAs.

Diese Übungen dienen dazu, Sie auf verschiedene Aspekte der in den kommenden Wochen in den Übungen genutzten Werkzeuge aufmerksam zu machen.

* Wenn Sie in Ihrem bisherigen Studienverlauf noch nicht viel mit Python zu tun hatten, schauen Sie doch gerne einmal bei ILIAS unter "Lernressourcen" nach. Ich habe Ihnen dort Inhalte hinterlegt, die Sie nutzen können, um sich im Selbststudium mit Python vertrauter zu machen.

## 2.1.1 Shapes und Co.

Bei vielen Data Science Projekten werden Daten zunächst zugänglich gemacht, sodass sie als Numpy Arrays vorliegen. Das Verständnis von *Shapes* solcher Arrays ist eine wichtige Voraussetzung für eine produktive Arbeit mit diesen Datenstrukturen.

Nehmen Sie die Folien zur heutigen Vorlesung zur Hand.

**Ihre Aufgaben**

(1) Betrachten Sie den untenstehenden Code. Beantworten Sie: Welchen [Shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) hat das Numpy Array `a`? 

In [4]:
import numpy as np
a = np.array([5, 10, 15, 20])
b = a.shape
c = a.T
print (a, b, c)


[ 5 10 15 20] (4,) [ 5 10 15 20]


(2) Lässt sich das Array `a` als (mathematischen) Vektor interpretieren? Wenn `a` ein Vektor ist, können Sie ihn [transponieren](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)?
Antwort:
ja, siehe c im Oben.

(3) Betrachten Sie das unten stehende Array `b`. Erzeugen Sie aus `b` bitte zwei neue Arrays `c` und `d`: `c` soll ein Spaltenvektor sein, und `d` soll ein Zeilenvektor sein. Wie gehen Sie vor?

In [9]:
b = np.array([2, 4, 6, 8, 10])
c = b.T
d = b
print(b, c, d)

[ 2  4  6  8 10] [ 2  4  6  8 10] [ 2  4  6  8 10]


Lässt sich `c` bzw. `d` transponieren? Warum? nein, Numpy's transpose() (alias T) stellt(eng. reverse) das shape von array andersrum(. Dies bedeutet für ein 1 dimensionale array wie 'b' keine effect.

(4) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Zeile `k[0, 1] = 10` das Array `m` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Antwort:
Ja, np.array() ist zwar ein dynamisches Feld und k wird sich wie ein Zeiger bei der c++ Sprache verhält. Daher ist 'm' eine Kopie von Zeiger der gewählten Elementen von matrix 'm'. In diesem Fall wurde an der Stelle erste Zeile zweite spalte von Matrix 10 geschrieben.

In [16]:
k = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m = k[:2, 1:3]
k[0, 1] = 10
print ( k, '\n', m)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 [[10  3]
 [ 6  7]]


(5) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Änderung des Arrays `p` der Inhalt von `q` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?
Antwort:
Nein, weil hier(im zweiten Zeile) explizit die Kopie von zweiten und dritte Element aus erste Spalte von Matrix 'p' gemacht wurde(keine Kopie von Zeiger)

In [28]:
p = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
q = p[[1, 2], 0]
p[1, 0] = 25
print(q, '\t\n', p)

[5 9] 	
 [[ 1  2  3  4]
 [25  6  7  8]
 [ 9 10 11 12]]


## 2.1.2 Broadcasting - Teil 1

Nehmen Sie sich die Folien zur heutigen Vorlesung zur Hand. Unten sehen Sie eine Operation mit zwei Numpy Arrays `a` und `b`.

**Ihre Aufgaben**

(1) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.
Antwort:
die beiden arrays sind gleich dimension und gleich größ und daher wird auf jedem component des linken arrays aus Komponenten der rechten hingefügt.

In [20]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

# Ihre Vorhersagen
shape = (3,)
ergebnis = np.array([5, 7, 9])
print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



(2) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.
Antwort:
  The new-axis funktioniert wie eine reshape zur Konvertierung array[4,5,6] in einer spalte und damit wegen
  der unterschiedlichen Dimensionen der Operanden füllen sich die beiden Seite der Add operation mit zusätzliche dimension zur Anpassung auf. D.h. 'a' und 'b' bekommen ein shape (3,3) und somit das Ergebnis auch.

In [47]:
a = np.array([1, 2, 3])
# a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])[:, np.newaxis]
bt = np.array([[4, 5, 6],[1,2,3]])[:, np.newaxis]
print(bt[:].shape)
print(b, '\n', b.shape)
print(a, '\n',a.shape)
c = a + b
print(c)
shape = (3, 3) # Ihre Vorhersage
ergebnis = np.array([[5,6,7],[6,7,8],[7,8,9]])
print('{}\n'.format('Shape Korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

(2, 1, 3)
[[4]
 [5]
 [6]] 
 (3, 1)
[1 2 3] 
 (3,)
[[5 6 7]
 [6 7 8]
 [7 8 9]]
Shape Korrekt.

Ergebnis korrekt.



(3) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [ ]:
a = np.array([[1, 0, 0], [0, 0, 2]])
b = np.ones(12).reshape((4, 1, 3))
print(b)
# print(np.ones((3, 2,3)))
c = a * b
# print(c)
shape = (-1,) # Ihre Vorhersage
ergebnis = np.array([-1]) # Ich vermute, dass sie hierüber länger nachdenken werden.

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

In [69]:
## 2.1.3 Broadcasting Teil 2

Ein häufiger Vorverarbeitungsschritt, der Ihnen in verschiedenen Data Science Projekten begegnen wird, ist die Normierung von Daten. Häufig werden dabei Datensätze, z.B. Zeitreihen, auf Mittelwert $0$ und Standardabweichung $1$ normiert. Dieser Vorgang wird auch *z-scoring* (oder: *Standardisierung*) genannt:

Sei $x_i$ der $i$-te Datenpunkt einer Zeitreihe. Dann ist der z-score dieses Datenpunkts definiert als

$$\tilde{x}_i = \frac{x_i - \bar{x}}{\sigma},$$

wobei $\bar{x}$ der Mittelwert sowie $\sigma$ die Standardabweichung der Zeitreihe bezeichnen.

Das in der unten stehenden Code-Zelle definierte Numpy Array `X` enthält 5 Zeitreihen (Spalten) mit je 30 Einträgen (Zeilen).

* Nutzen Sie Broadcasting sowie [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) und [np.std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html), um die Zeitreihen auf Mittelwert 0 und Varianz 1 zu normieren. Die transformierten Zeitreihen sollen im Numpy Array `Y` gespeichert werden. Dabei schreiben Sie nur eine Zeile Code, um die Zeitreihen zu transformieren.
* Beachten Sie das `axis` Argument bei `np.mean` und `np.std`.

SyntaxError: invalid syntax (3415409566.py, line 3)

## 2.1.3 Broadcasting Teil 2

Ein häufiger Vorverarbeitungsschritt, der Ihnen in verschiedenen Data Science Projekten begegnen wird, ist die Normierung von Daten. Häufig werden dabei Datensätze, z.B. Zeitreihen, auf Mittelwert $0$ und Standardabweichung $1$ normiert. Dieser Vorgang wird auch *z-scoring* (oder: *Standardisierung*) genannt:

Sei $x_i$ der $i$-te Datenpunkt einer Zeitreihe. Dann ist der z-score dieses Datenpunkts definiert als

$$\tilde{x}_i = \frac{x_i - \bar{x}}{\sigma},$$ 

wobei $\bar{x}$ der Mittelwert sowie $\sigma$ die Standardabweichung der Zeitreihe bezeichnen.

Das in der unten stehenden Code-Zelle definierte Numpy Array `X` enthält 5 Zeitreihen (Spalten) mit je 30 Einträgen (Zeilen). 

* Nutzen Sie Broadcasting sowie [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) und [np.std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html), um die Zeitreihen auf Mittelwert 0 und Varianz 1 zu normieren. Die transformierten Zeitreihen sollen im Numpy Array `Y` gespeichert werden. Dabei schreiben Sie nur eine Zeile Code, um die Zeitreihen zu transformieren.
* Beachten Sie das `axis` Argument bei `np.mean` und `np.std`.

import numpy as np
np.random.seed(0)

X = np.random.random((30, 5))

# Ihr Ergebnis: Y = 

In [ ]:
import numpy as np
np.random.seed(0)

X = np.random.random((30, 5))

# Ihr Ergebnis: Y = 

(2) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [ ]:
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]]) 
   
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 

vorhersage = np.array([-1]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

(3) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [ ]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]]) 

y = x[1:4,[1,2]] # Kombination von Slicing und Advanced Indexing

vorhersage = np.array([-1]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))